spring.application.name=echolife-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/echolife
spring.datasource.username=postgres
spring.datasource.password=Gana@9380

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true